## 一、Algorithm

## LeetCode[17] 电话号码的字母组

题目描述:
  给定一个仅包含数字 2-9 的字符串，返回所有它能表示的字母组合。
  给出数字到字母的映射如下（与电话按键相同）。注意 1 不对应任何字母。

```cpp
#include <iostream>
#include <vector>
#include <string>
#include <cassert>

using namespace std;

/// 时间复杂度: O(2^len(s))
/// 空间复杂度: O(len(s))
class Solution {

private:
	const string letterMap[10] = {
		" ",    //0
		"",     //1
		"abc",  //2
		"def",  //3
		"ghi",  //4
		"jkl",  //5
		"mno",  //6
		"pqrs", //7
		"tuv",  //8
		"wxyz"  //9
	};

	vector<string> res;

	// s中保存了此时从digits[0...index-1]翻译得到的一个字母字符串
	// 寻找和digits[index]匹配的字母, 获得digits[0...index]翻译得到的解
	void findCombination(const string &digits, int index, const string &s) {

		cout << index << " : " << s << endl;
		if (index == digits.size()) {
			res.push_back(s);
			cout << "get " << s << " , return" << endl;
			return;
		}

		char c = digits[index];

		assert(c >= '0' && c <= '9' && c != '1');
		string letters = letterMap[c - '0'];
		for (int i = 0; i < letters.size(); i++) {
			cout << "digits[" << index << "] = " << c << " , use " << letters[i] << endl;
			findCombination(digits, index + 1, s + letters[i]);
		}

		cout << "digits[" << index << "] = " << c << " complete, return" << endl;

		return;
	}

public:
	vector<string> letterCombinations(string digits) {

		res.clear();
		if (digits == "")
			return res;

		findCombination(digits, 0, "");

		return res;
	}
};

int main() {

	vector<string> res = Solution().letterCombinations("23");

	for (int i = 0; i < res.size(); i++)
		cout << res[i] << endl;

	return 0;
}
```

## 二、Review

C#中Transactions的使用。

文章链接：https://stackoverflow.com/questions/224689/transactions-in-net

title：《[Transactions in .net](https://stackoverflow.com/questions/224689/transactions-in-net)》

  文章总结了C#中的 Transactions 主要有两种Transactions方式connection transactions和ambient transactions。

1.connection transactions：

```cpp
using (IDbTransaction tran = conn.BeginTransaction()) {
    try {
        // your code
        tran.Commit();
    }  catch {
        tran.Rollback();
        throw;
    }
}
```

2.ambient transactions：

```cpp
using(TransactionScope tran = new TransactionScope()) {
    CallAMethodThatDoesSomeWork();
    CallAMethodThatDoesSomeMoreWork();
    tran.Complete();
}
```

## 三、Tip

学习[Revit二次开发]计算几何实体的面积和体积：

**项目完整代码：**

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Autodesk.Revit.UI;
using Autodesk.Revit.DB;
using Autodesk.Revit.Attributes;

namespace SolidPractise
{
    [TransactionAttribute(TransactionMode.Manual)]
    [RegenerationAttribute(RegenerationOption.Manual)]
    public class Class1 : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            UIDocument uidoc = commandData.Application.ActiveUIDocument;//UIDocument:代表在Revit用户界面中打开的Autodesk Revit项目的对象。
            Autodesk.Revit.DB.Document revitDoc = uidoc.Document;//Document:表示打开的Autodesk Revit项目的对象
            ICollection<ElementId> ids = uidoc.Selection.GetElementIds();//ICollection:元素Id收集器
            Element selElem = uidoc.Document.GetElement(ids.First());//获取第一个元素
            GeometryElement ge = selElem.get_Geometry(new Options());

            double area = 0;//定义几何面积
            double volume = 0;//定义几何体积
            int triangleCount = 0; //三角网格数

            foreach(GeometryObject gObj in ge) //遍历集合ge中每一个元素
            {
                if(gObj is Solid) //如果元素gObj是实体
                {
                    Solid sd = gObj as Solid; //将gObj转换成实体
                    foreach(Face face in sd.Faces)  //遍历sd.Faces中每一个面
                    {
                        area += face.Area * 0.3048 * 0.3048;//Revit中的单位是英尺,需进行单位转换
                        Mesh mesh = face.Triangulate(0.5);
                        triangleCount += mesh.NumTriangles; //计算三角网格数
                    }
                    volume += sd.Volume * 0.3048 * 0.3048 * 0.3048;
                }
            }

            TaskDialog.Show("计算", "面积总和为" + area.ToString() + "平方米" + "\n"
                + "体积为" + volume.ToString("0.000") + "立方米" + "\n"
                + "三角网格数为" + triangleCount.ToString());


            return Result.Succeeded;
        }
    }

}

```

**效果：**
在Revit中画一道墙，点击选中此道墙，加载应用程序：
![](https://ws1.sinaimg.cn/large/005SvaFtgy1fy1qyy416pj30o80l2dgp.jpg)

## 四、Share

本文对TransactionIn.NET做了详细的解析和应用

title:**TransactionIn.NET**

link:https://www.c-sharpcorner.com/article/transaction-in-net/
